// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProductOffer.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Protos.Service1 {
  public static partial class ProductOfferService
  {
    static readonly string __ServiceName = "ProductOfferService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protos.Service1.Empty> __Marshaller_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protos.Service1.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protos.Service1.Offers> __Marshaller_Offers = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protos.Service1.Offers.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protos.Service1.GetOfferDetailRequest> __Marshaller_GetOfferDetailRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protos.Service1.GetOfferDetailRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protos.Service1.OfferDetail> __Marshaller_OfferDetail = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protos.Service1.OfferDetail.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protos.Service1.CreateOfferDetailRequest> __Marshaller_CreateOfferDetailRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protos.Service1.CreateOfferDetailRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protos.Service1.CreateOfferFromMegaRequest> __Marshaller_CreateOfferFromMegaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protos.Service1.CreateOfferFromMegaRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protos.Service1.UpdateOfferDetailRequest> __Marshaller_UpdateOfferDetailRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protos.Service1.UpdateOfferDetailRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protos.Service1.DeleteOfferDetailRequest> __Marshaller_DeleteOfferDetailRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protos.Service1.DeleteOfferDetailRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protos.Service1.DeleteOfferDetailResponse> __Marshaller_DeleteOfferDetailResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protos.Service1.DeleteOfferDetailResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protos.Service1.PingReply> __Marshaller_PingReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protos.Service1.PingReply.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protos.Service1.Empty, global::Protos.Service1.Offers> __Method_GetOfferList = new grpc::Method<global::Protos.Service1.Empty, global::Protos.Service1.Offers>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOfferList",
        __Marshaller_Empty,
        __Marshaller_Offers);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protos.Service1.GetOfferDetailRequest, global::Protos.Service1.OfferDetail> __Method_GetOffer = new grpc::Method<global::Protos.Service1.GetOfferDetailRequest, global::Protos.Service1.OfferDetail>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOffer",
        __Marshaller_GetOfferDetailRequest,
        __Marshaller_OfferDetail);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protos.Service1.CreateOfferDetailRequest, global::Protos.Service1.OfferDetail> __Method_CreateOffer = new grpc::Method<global::Protos.Service1.CreateOfferDetailRequest, global::Protos.Service1.OfferDetail>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateOffer",
        __Marshaller_CreateOfferDetailRequest,
        __Marshaller_OfferDetail);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protos.Service1.CreateOfferFromMegaRequest, global::Protos.Service1.OfferDetail> __Method_CreateOfferFromMegaOffer = new grpc::Method<global::Protos.Service1.CreateOfferFromMegaRequest, global::Protos.Service1.OfferDetail>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateOfferFromMegaOffer",
        __Marshaller_CreateOfferFromMegaRequest,
        __Marshaller_OfferDetail);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protos.Service1.UpdateOfferDetailRequest, global::Protos.Service1.OfferDetail> __Method_UpdateOffer = new grpc::Method<global::Protos.Service1.UpdateOfferDetailRequest, global::Protos.Service1.OfferDetail>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateOffer",
        __Marshaller_UpdateOfferDetailRequest,
        __Marshaller_OfferDetail);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protos.Service1.DeleteOfferDetailRequest, global::Protos.Service1.DeleteOfferDetailResponse> __Method_DeleteOffer = new grpc::Method<global::Protos.Service1.DeleteOfferDetailRequest, global::Protos.Service1.DeleteOfferDetailResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteOffer",
        __Marshaller_DeleteOfferDetailRequest,
        __Marshaller_DeleteOfferDetailResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protos.Service1.Empty, global::Protos.Service1.PingReply> __Method_PingMessage = new grpc::Method<global::Protos.Service1.Empty, global::Protos.Service1.PingReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PingMessage",
        __Marshaller_Empty,
        __Marshaller_PingReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protos.Service1.Empty, global::Protos.Service1.PingReply> __Method_PongMessage = new grpc::Method<global::Protos.Service1.Empty, global::Protos.Service1.PingReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PongMessage",
        __Marshaller_Empty,
        __Marshaller_PingReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Protos.Service1.ProductOfferReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ProductOfferService</summary>
    [grpc::BindServiceMethod(typeof(ProductOfferService), "BindService")]
    public abstract partial class ProductOfferServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protos.Service1.Offers> GetOfferList(global::Protos.Service1.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protos.Service1.OfferDetail> GetOffer(global::Protos.Service1.GetOfferDetailRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protos.Service1.OfferDetail> CreateOffer(global::Protos.Service1.CreateOfferDetailRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protos.Service1.OfferDetail> CreateOfferFromMegaOffer(global::Protos.Service1.CreateOfferFromMegaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protos.Service1.OfferDetail> UpdateOffer(global::Protos.Service1.UpdateOfferDetailRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protos.Service1.DeleteOfferDetailResponse> DeleteOffer(global::Protos.Service1.DeleteOfferDetailRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protos.Service1.PingReply> PingMessage(global::Protos.Service1.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protos.Service1.PingReply> PongMessage(global::Protos.Service1.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ProductOfferService</summary>
    public partial class ProductOfferServiceClient : grpc::ClientBase<ProductOfferServiceClient>
    {
      /// <summary>Creates a new client for ProductOfferService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ProductOfferServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ProductOfferService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ProductOfferServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ProductOfferServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ProductOfferServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.Offers GetOfferList(global::Protos.Service1.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOfferList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.Offers GetOfferList(global::Protos.Service1.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOfferList, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.Offers> GetOfferListAsync(global::Protos.Service1.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOfferListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.Offers> GetOfferListAsync(global::Protos.Service1.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOfferList, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.OfferDetail GetOffer(global::Protos.Service1.GetOfferDetailRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOffer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.OfferDetail GetOffer(global::Protos.Service1.GetOfferDetailRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOffer, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.OfferDetail> GetOfferAsync(global::Protos.Service1.GetOfferDetailRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOfferAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.OfferDetail> GetOfferAsync(global::Protos.Service1.GetOfferDetailRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOffer, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.OfferDetail CreateOffer(global::Protos.Service1.CreateOfferDetailRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateOffer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.OfferDetail CreateOffer(global::Protos.Service1.CreateOfferDetailRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateOffer, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.OfferDetail> CreateOfferAsync(global::Protos.Service1.CreateOfferDetailRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateOfferAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.OfferDetail> CreateOfferAsync(global::Protos.Service1.CreateOfferDetailRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateOffer, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.OfferDetail CreateOfferFromMegaOffer(global::Protos.Service1.CreateOfferFromMegaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateOfferFromMegaOffer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.OfferDetail CreateOfferFromMegaOffer(global::Protos.Service1.CreateOfferFromMegaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateOfferFromMegaOffer, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.OfferDetail> CreateOfferFromMegaOfferAsync(global::Protos.Service1.CreateOfferFromMegaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateOfferFromMegaOfferAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.OfferDetail> CreateOfferFromMegaOfferAsync(global::Protos.Service1.CreateOfferFromMegaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateOfferFromMegaOffer, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.OfferDetail UpdateOffer(global::Protos.Service1.UpdateOfferDetailRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateOffer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.OfferDetail UpdateOffer(global::Protos.Service1.UpdateOfferDetailRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateOffer, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.OfferDetail> UpdateOfferAsync(global::Protos.Service1.UpdateOfferDetailRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateOfferAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.OfferDetail> UpdateOfferAsync(global::Protos.Service1.UpdateOfferDetailRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateOffer, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.DeleteOfferDetailResponse DeleteOffer(global::Protos.Service1.DeleteOfferDetailRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteOffer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.DeleteOfferDetailResponse DeleteOffer(global::Protos.Service1.DeleteOfferDetailRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteOffer, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.DeleteOfferDetailResponse> DeleteOfferAsync(global::Protos.Service1.DeleteOfferDetailRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteOfferAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.DeleteOfferDetailResponse> DeleteOfferAsync(global::Protos.Service1.DeleteOfferDetailRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteOffer, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.PingReply PingMessage(global::Protos.Service1.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.PingReply PingMessage(global::Protos.Service1.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PingMessage, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.PingReply> PingMessageAsync(global::Protos.Service1.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.PingReply> PingMessageAsync(global::Protos.Service1.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PingMessage, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.PingReply PongMessage(global::Protos.Service1.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PongMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Protos.Service1.PingReply PongMessage(global::Protos.Service1.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PongMessage, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.PingReply> PongMessageAsync(global::Protos.Service1.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PongMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Protos.Service1.PingReply> PongMessageAsync(global::Protos.Service1.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PongMessage, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ProductOfferServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ProductOfferServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ProductOfferServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetOfferList, serviceImpl.GetOfferList)
          .AddMethod(__Method_GetOffer, serviceImpl.GetOffer)
          .AddMethod(__Method_CreateOffer, serviceImpl.CreateOffer)
          .AddMethod(__Method_CreateOfferFromMegaOffer, serviceImpl.CreateOfferFromMegaOffer)
          .AddMethod(__Method_UpdateOffer, serviceImpl.UpdateOffer)
          .AddMethod(__Method_DeleteOffer, serviceImpl.DeleteOffer)
          .AddMethod(__Method_PingMessage, serviceImpl.PingMessage)
          .AddMethod(__Method_PongMessage, serviceImpl.PongMessage).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ProductOfferServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetOfferList, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protos.Service1.Empty, global::Protos.Service1.Offers>(serviceImpl.GetOfferList));
      serviceBinder.AddMethod(__Method_GetOffer, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protos.Service1.GetOfferDetailRequest, global::Protos.Service1.OfferDetail>(serviceImpl.GetOffer));
      serviceBinder.AddMethod(__Method_CreateOffer, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protos.Service1.CreateOfferDetailRequest, global::Protos.Service1.OfferDetail>(serviceImpl.CreateOffer));
      serviceBinder.AddMethod(__Method_CreateOfferFromMegaOffer, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protos.Service1.CreateOfferFromMegaRequest, global::Protos.Service1.OfferDetail>(serviceImpl.CreateOfferFromMegaOffer));
      serviceBinder.AddMethod(__Method_UpdateOffer, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protos.Service1.UpdateOfferDetailRequest, global::Protos.Service1.OfferDetail>(serviceImpl.UpdateOffer));
      serviceBinder.AddMethod(__Method_DeleteOffer, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protos.Service1.DeleteOfferDetailRequest, global::Protos.Service1.DeleteOfferDetailResponse>(serviceImpl.DeleteOffer));
      serviceBinder.AddMethod(__Method_PingMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protos.Service1.Empty, global::Protos.Service1.PingReply>(serviceImpl.PingMessage));
      serviceBinder.AddMethod(__Method_PongMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protos.Service1.Empty, global::Protos.Service1.PingReply>(serviceImpl.PongMessage));
    }

  }
}
#endregion
